name: Run examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: sudo apt-get install python3-setuptools && \
            python3 -m pip install --upgrade pip  && \
            pip3 install -r requirements.txt 
